### ISSUE TITLE
Documentation incomplete? Build would not run

### ISSUE THREAD

**Issue by tinne** [adessoAG/GitStalkerBootstrapUI#1]
Windows 10 64bit, npm 6.4.1 / node 8.12.0.
```console
$ npm install ng-cli -g
C:\Users\tinnefeld\AppData\Roaming\npm\ng -> C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\bin\ng.js
+ ng-cli@0.7.0
added 59 packages from 37 contributors in 1.567s

$ ng serve
C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve\lib\sync.js:45
    throw err;
    ^

Error: Cannot find module 'ng-factory' from 'D:\Projekte\adesso\GitStalker\GitStalkerBootstrapUI'
    at Function.module.exports [as sync] (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve\lib\sync.js:43:15)
    at module.exports (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\resolve-require\lib\index.js:10:24)
    at Command.<anonymous> (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\lib\index.js:49:5)
    at Command.listener (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:654:12)
    at Command.parse (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\tinnefeld\AppData\Roaming\npm\node_modules\ng-cli\lib\index.js:55:9)
    at Module._compile (module.js:653:30)
```

**Comment by tinne** [comment]
The following helped: manually install both angular/cli and angular/compiler-cli, then collect dependencies:

> npm install -g @angular/cli @angular/compiler-cli
> npm install

These lines should be added at the beginning of README.md. Thanks to [Filip Molcik](https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/).

**Comment by s-gbz** [comment]
The project hasn't been prepared for public use yet, but you're right. Thank you 👍
